### ISSUE TITLE
How to input different size images on testing when running pix2pix model

### ISSUE THREAD

**Issue by universewill** [junyanz/pytorch-CycleGAN-and-pix2pix#487]
I trained pix2pix model with 256x256 size crop images.
I got several input images with different sizes, I want to feed them to pix2pix model. I want to get a result which has same width and height as origin image.How to achieve this?

I read the #359 issue and set resize_and_crop to none, but the error tells me that pix2pix only support resize_and_crop mode.

My test command:
```
python3 test.py --dataroot ./pix2pix_data --name my_pix2pix --model pix2pix --direction AtoB --resize_or_crop none
```

The error:
```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    data_loader = CreateDataLoader(opt)
  File "/pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 49, in CreateDataLoader
    data_loader = CustomDatasetDataLoader(opt)
  File "pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 61, in __init__
    self.dataset = create_dataset(opt)
  File "pytorch-CycleGAN-and-pix2pix/data/__init__.py", line 38, in create_dataset
    instance = dataset(opt)
  File "/pytorch-CycleGAN-and-pix2pix/data/aligned_dataset.py", line 19, in __init__
    assert(opt.resize_or_crop == 'resize_and_crop')  # only support this mode
AssertionError
```

**Comment by junyanz** [comment]
Good call. I fixed it with the latest commit. Could you try it again?

**Comment by universewill** [comment]
Sorry for the late response. I pull the code, and run command like this:
```
python3 test.py --dataroot /path/pix2pix_data --name my_pix2pix --model pix2pix --direction AtoB --resize_or_crop none
```

The error says:
```
usage: test.py [-h] --dataroot DATAROOT [--name NAME] [--gpu_ids GPU_IDS]
               [--checkpoints_dir CHECKPOINTS_DIR] [--model MODEL]
               [--input_nc INPUT_NC] [--output_nc OUTPUT_NC] [--ngf NGF]
               [--ndf NDF] [--netD NETD] [--netG NETG]
               [--n_layers_D N_LAYERS_D] [--norm NORM] [--init_type INIT_TYPE]
               [--init_gain INIT_GAIN] [--no_dropout]
               [--dataset_mode DATASET_MODE] [--direction DIRECTION]
               [--serial_batches] [--num_threads NUM_THREADS]
               [--batch_size BATCH_SIZE] [--load_size LOAD_SIZE]
               [--crop_size CROP_SIZE] [--max_dataset_size MAX_DATASET_SIZE]
               [--preprocess PREPROCESS] [--no_flip]
               [--display_winsize DISPLAY_WINSIZE] [--epoch EPOCH]
               [--load_iter LOAD_ITER] [--verbose] [--suffix SUFFIX]
               [--ntest NTEST] [--results_dir RESULTS_DIR]
               [--aspect_ratio ASPECT_RATIO] [--phase PHASE] [--eval]
               [--num_test NUM_TEST]
test.py: error: unrecognized arguments: --resize_or_crop none
```

It seems that the resize_or_crop parameter is removed?
I then set the preprocess parameter to none, but still get cropped results. here is my command:
```
python3 test.py --dataroot /path/pix2pix_data --name my_pix2pix --model pix2pix --direction AtoB -- preprocess none
```

**Comment by junyanz** [comment]
We recently changed it to `-preprocess`.

**Comment by universewill** [comment]
I then set the preprocess parameter to none, but still get resize and cropped results. here is my command:
```
python3 test.py --dataroot /path/pix2pix_data --name my_pix2pix --model pix2pix --direction AtoB --preprocess none
```

I add print code to test.py to print opt, here is the the print result on terminal:
```
Namespace(aspect_ratio=1.0, batch_size=1, checkpoints_dir='./checkpoints', crop_size=256, dataroot='/path/pix2pix_data', dataset_mode='aligned', direction='AtoB', display_id=-1, display_winsize=256, epoch='latest', eval=False, gpu_ids=[0], init_gain=0.02, init_type='normal', input_nc=3, isTrain=False, load_iter=0, load_size=256, max_dataset_size=inf, model='pix2pix', n_layers_D=3, name='my_pix2pix', ndf=64, netD='basic', netG='unet_256', ngf=64, no_dropout=False, no_flip=True, norm='batch', ntest=inf, num_test=50, num_threads=1, output_nc=3, phase='test', preprocess='none', results_dir='./results/', serial_batches=True, suffix='', verbose=False)
```

@junyanz

**Comment by junyanz** [comment]
Maybe you want to give us more details. I just tried the following command. 
```python
python train.py --dataroot ./datasets/horse2zebra --name horse2zebra_cyclegan --model cycle_gan --preprocess none
```
It works on my machine.

**Comment by universewill** [comment]
Will you try it on pix2pix model? It can run well with cyclegan model, but not pix2pix on my machine.
@junyanz @taesungp

**Comment by alsugiliazova** [comment]
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 65 but got size 64 for tensor number 1 in the list
Can you help me pleae?
I used option --preprocess none.
The image size needs to be a multiple of 4. The loaded image size was (775, 522), so it was adjusted to (776, 520). This adjustment will be done to all images whose sizes are not multiples of 4. I got this message first.

**Comment by junyanz** [comment]
What is your training command? and how big is your training image?

**Comment by alsugiliazova** [comment]
> What is your training command? and how big is your training image?

 python train.py --dataroot cell_data --model pix2pix --direction BtoA --display_id -1 --gpu_id 1 --preprocess none 
Training image is 262 to 262 pixels.
